# Generated by Django 3.0.5 on 2026-02-03 08:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stocks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('promo_type', models.CharField(choices=[('nxm', 'NxM (Ej: 2x1, 3x2)'), ('quantity_discount', 'Descuento por Cantidad'), ('combo', 'Combo'), ('second_unit', 'Segunda Unidad con Descuento'), ('simple_discount', 'Descuento Porcentual')], max_length=30, verbose_name='Tipo de Promoción')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('active', 'Activa'), ('paused', 'Pausada'), ('finished', 'Finalizada')], default='draft', max_length=20, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('priority', models.PositiveIntegerField(default=50, help_text='Mayor número = Mayor prioridad', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Prioridad')),
                ('is_combinable', models.BooleanField(default=True, help_text='¿Se puede combinar con otras promociones?', verbose_name='Combinable')),
                ('monday', models.BooleanField(default=True, verbose_name='Lunes')),
                ('tuesday', models.BooleanField(default=True, verbose_name='Martes')),
                ('wednesday', models.BooleanField(default=True, verbose_name='Miércoles')),
                ('thursday', models.BooleanField(default=True, verbose_name='Jueves')),
                ('friday', models.BooleanField(default=True, verbose_name='Viernes')),
                ('saturday', models.BooleanField(default=True, verbose_name='Sábado')),
                ('sunday', models.BooleanField(default=True, verbose_name='Domingo')),
                ('hour_start', models.TimeField(blank=True, null=True, verbose_name='Hora Inicio')),
                ('hour_end', models.TimeField(blank=True, null=True, verbose_name='Hora Fin')),
                ('min_quantity', models.PositiveIntegerField(default=1, help_text='Cantidad mínima de productos para aplicar', verbose_name='Cantidad Mínima')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Mínimo de Compra')),
                ('max_uses_per_sale', models.PositiveIntegerField(default=0, help_text='0 = Sin límite', verbose_name='Máximo Usos por Venta')),
                ('quantity_required', models.PositiveIntegerField(default=2, help_text='Ej: 2 para promoción 2x1', verbose_name='Cantidad Requerida')),
                ('quantity_charged', models.PositiveIntegerField(default=1, help_text='Ej: 1 para promoción 2x1', verbose_name='Cantidad Cobrada')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento (%)')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Descuento Fijo ($)')),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='Precio final del combo', max_digits=10, null=True, verbose_name='Precio Final (Combos)')),
                ('second_unit_discount', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Descuento 2da Unidad (%)')),
                ('usages', models.PositiveIntegerField(default=0, verbose_name='Usos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_promotions', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_promotions', to='stocks.Product')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_products', to='promotions.Promotion')),
            ],
            options={
                'verbose_name': 'Producto en Promoción',
                'verbose_name_plural': 'Productos en Promoción',
                'unique_together': {('promotion', 'product')},
            },
        ),
        migrations.AddField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(related_name='promotions', through='promotions.PromotionProduct', to='stocks.Product', verbose_name='Productos'),
        ),
    ]
