# Generated by Django 4.2.27 on 2026-04-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_id_alter_promotionproduct_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='promo_type',
            field=models.CharField(choices=[('nxm', 'NxM (Ej: 2x1, 3x2)'), ('nx_fixed_price', 'N por Precio Fijo (Ej: 2x$500, 3x$1000)'), ('quantity_discount', 'Descuento por Cantidad'), ('combo', 'Combo'), ('second_unit', 'Segunda Unidad con Descuento'), ('simple_discount', 'Descuento Porcentual')], max_length=30, verbose_name='Tipo de Promoción'),
        ),
    ]
