# Generated by Django 4.2.27 on 2026-03-30 04:22

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0003_alter_purchase_id_alter_purchaseitem_id_and_more'),
        ('stocks', '0010_product_granel_price_weight_grams_product_is_granel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('quantity_purchased', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad Comprada')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad Restante')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo Unitario')),
                ('purchased_at', models.DateTimeField(verbose_name='Fecha de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_batches', to='stocks.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='purchase.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Lote de Stock',
                'verbose_name_plural': 'Lotes de Stock',
                'ordering': ['purchased_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShrinkageAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoretical_grams', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Teórico (g)')),
                ('actual_grams', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso Real (g)')),
                ('shrinkage_grams', models.DecimalField(decimal_places=2, help_text='Positivo = sobrante, negativo = merma', max_digits=12, verbose_name='Diferencia (g)')),
                ('shrinkage_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Merma %')),
                ('reason', models.CharField(choices=[('picoteo', 'Picoteo/Degustación'), ('humedad', 'Humedad/Evaporación'), ('pesaje', 'Error de Pesaje'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Motivo')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('stock_adjusted', models.BooleanField(default=False, help_text='Si se aplicó el ajuste al stock del producto granel', verbose_name='Stock Ajustado')),
                ('audited_at', models.DateTimeField(auto_now_add=True)),
                ('audited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shrinkage_audits', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por')),
                ('granel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shrinkage_audits', to='stocks.product', verbose_name='Producto Granel')),
            ],
            options={
                'verbose_name': 'Auditoría de Merma',
                'verbose_name_plural': 'Auditorías de Merma',
                'ordering': ['-audited_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkToGranelTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_transferred', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos Transferidos')),
                ('bulk_cost_per_gram', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo por Gramo (bulto)')),
                ('granel_stock_before', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Granel Antes (g)')),
                ('granel_weighted_cost_before', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Ponderado Antes ($/g)')),
                ('granel_stock_after', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Granel Después (g)')),
                ('granel_weighted_cost_after', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Ponderado Después ($/g)')),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('bulk_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granel_transfers_out', to='stocks.product', verbose_name='Producto Bulto (origen)')),
                ('granel_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='granel_transfers_in', to='stocks.product', verbose_name='Producto Granel (destino)')),
                ('source_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granel_transfers', to='granel.stockbatch', verbose_name='Lote Origen')),
                ('transferred_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granel_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Transferido por')),
            ],
            options={
                'verbose_name': 'Transferencia Bulto a Granel',
                'verbose_name_plural': 'Transferencias Bulto a Granel',
                'ordering': ['-transferred_at'],
            },
        ),
    ]
