# Generated by Django 4.2.27 on 2026-03-31 01:35

from django.db import migrations


def copy_batches_to_stocks(apps, schema_editor):
    """Copy data from granel_stockbatch to stocks_stockbatch."""
    OldBatch = apps.get_model('granel', 'StockBatch')
    NewBatch = apps.get_model('stocks', 'StockBatch')

    for old in OldBatch.objects.all():
        NewBatch.objects.create(
            id=old.id,
            product_id=old.product_id,
            purchase_id=old.purchase_id,
            supplier_name=old.supplier_name,
            quantity_purchased=old.quantity_purchased,
            quantity_remaining=old.quantity_remaining,
            purchase_price=old.unit_cost,  # renamed field
            purchased_at=old.purchased_at,
            created_by_id=old.created_by_id,
            created_at=old.created_at,
            notes=old.notes,
        )


def copy_batches_back(apps, schema_editor):
    """Reverse: copy from stocks_stockbatch back to granel_stockbatch."""
    OldBatch = apps.get_model('granel', 'StockBatch')
    NewBatch = apps.get_model('stocks', 'StockBatch')

    for new in NewBatch.objects.all():
        if not OldBatch.objects.filter(id=new.id).exists():
            OldBatch.objects.create(
                id=new.id,
                product_id=new.product_id,
                purchase_id=new.purchase_id,
                supplier_name=new.supplier_name,
                quantity_purchased=new.quantity_purchased,
                quantity_remaining=new.quantity_remaining,
                unit_cost=new.purchase_price,
                purchased_at=new.purchased_at,
                created_by_id=new.created_by_id,
                created_at=new.created_at,
                notes=new.notes,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('granel', '0001_initial'),
        ('stocks', '0011_add_stockbatch_model'),
    ]

    operations = [
        migrations.RunPython(copy_batches_to_stocks, copy_batches_back),
    ]
