# Generated by Django 4.2.27 on 2026-03-31 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_add_stockbatch_model'),
        ('granel', '0002_migrate_stockbatch_to_stocks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktograneltransfer',
            name='source_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granel_transfers', to='stocks.stockbatch', verbose_name='Lote Origen'),
        ),
        migrations.DeleteModel(
            name='StockBatch',
        ),
    ]
