# Generated by Django 4.2.27 on 2026-03-31 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_add_stockbatch_model'),
        ('granel', '0003_alter_bulktograneltransfer_source_batch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarameleraComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notas')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bulk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_carameleras', to='stocks.product', verbose_name='Producto Bulto (gomitas/caramelos)')),
                ('caramelera', models.ForeignKey(limit_choices_to={'is_granel': True}, on_delete=django.db.models.deletion.CASCADE, related_name='components', to='stocks.product', verbose_name='Caramelera')),
            ],
            options={
                'verbose_name': 'Componente de Caramelera',
                'verbose_name_plural': 'Componentes de Caramelera',
                'ordering': ['bulk_product__name'],
                'unique_together': {('caramelera', 'bulk_product')},
            },
        ),
    ]
