# Generated by Django 4.2.27 on 2026-04-02 21:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granel', '0004_caramelera_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='carameleracomponent',
            name='proportion_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Gramos en receta'),
        ),
    ]
