# Generated by Django 4.2.27 on 2026-04-03 04:30

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_product_sale_price_250g'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('granel', '0005_carameleracomponent_proportion_grams'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caramelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('precio_100g', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por 100g ($)')),
                ('precio_cuarto', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio especial por exactamente 250g', max_digits=10, verbose_name='Precio 1/4 kg - 250g ($)')),
                ('stock_gramos_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Stock Actual (g)')),
                ('costo_ponderado_gramo', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Costo promedio ponderado, recalculado en cada apertura', max_digits=12, verbose_name='Costo Ponderado por Gramo ($/g)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Caramelera',
                'verbose_name_plural': 'Carameleras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, max_length=200, verbose_name='Marca')),
                ('costo_bulto', models.DecimalField(decimal_places=2, help_text='Cuánto costó la bolsa/bulto completa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo del Bulto ($)')),
                ('gramos_por_bulto', models.DecimalField(decimal_places=2, help_text='Cuántos gramos tiene cada bolsa', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Gramos por Bulto (g)')),
                ('stock_unidades', models.IntegerField(default=0, help_text='Cuántas bolsas quedan en depósito', verbose_name='Stock (unidades)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto Depósito',
                'verbose_name_plural': 'Productos Depósito',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='bulktograneltransfer',
            options={'ordering': ['-transferred_at'], 'verbose_name': 'Transferencia Bulto a Granel (legacy)', 'verbose_name_plural': 'Transferencias Bulto a Granel (legacy)'},
        ),
        migrations.AlterModelOptions(
            name='carameleracomponent',
            options={'ordering': ['bulk_product__name'], 'verbose_name': 'Componente de Caramelera (legacy)', 'verbose_name_plural': 'Componentes de Caramelera (legacy)'},
        ),
        migrations.AlterModelOptions(
            name='shrinkageaudit',
            options={'ordering': ['-audited_at'], 'verbose_name': 'Auditoría de Merma (legacy)', 'verbose_name_plural': 'Auditorías de Merma (legacy)'},
        ),
        migrations.AlterField(
            model_name='bulktograneltransfer',
            name='granel_weighted_cost_after',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Ponderado Después'),
        ),
        migrations.AlterField(
            model_name='bulktograneltransfer',
            name='granel_weighted_cost_before',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Costo Ponderado Antes'),
        ),
        migrations.AlterField(
            model_name='carameleracomponent',
            name='bulk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_carameleras', to='stocks.product', verbose_name='Producto Bulto'),
        ),
        migrations.AlterField(
            model_name='shrinkageaudit',
            name='shrinkage_grams',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Diferencia (g)'),
        ),
        migrations.AlterField(
            model_name='shrinkageaudit',
            name='stock_adjusted',
            field=models.BooleanField(default=False, verbose_name='Stock Ajustado'),
        ),
        migrations.CreateModel(
            name='VentaGranel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_vendidos', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos Vendidos')),
                ('tipo_venta', models.CharField(choices=[('cuarto', '1/4 kg (250g)'), ('libre', 'Gramos libres')], default='libre', max_length=10, verbose_name='Tipo de Venta')),
                ('precio_cobrado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Cobrado ($)')),
                ('costo_gramo_al_vender', models.DecimalField(decimal_places=6, help_text='Snapshot del costo ponderado al momento de la venta', max_digits=12, verbose_name='Costo/g al Vender')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo Total ($)')),
                ('ganancia', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ganancia ($)')),
                ('vendido_en', models.DateTimeField(auto_now_add=True)),
                ('pos_transaction_id', models.IntegerField(blank=True, help_text='Referencia a la transacción POS que originó esta venta', null=True, verbose_name='ID Transacción POS')),
                ('caramelera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='granel.caramelera', verbose_name='Caramelera')),
            ],
            options={
                'verbose_name': 'Venta Granel',
                'verbose_name_plural': 'Ventas Granel',
                'ordering': ['-vendido_en'],
            },
        ),
        migrations.AddField(
            model_name='caramelera',
            name='productos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Productos del depósito que pueden entrar en este mix', to='granel.productodeposito', verbose_name='Productos Autorizados'),
        ),
        migrations.CreateModel(
            name='AuditoriaCaramelera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema_gramos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Sistema (g)')),
                ('peso_real_balanza_gramos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso Real Balanza (g)')),
                ('diferencia_gramos', models.DecimalField(decimal_places=2, help_text='sistema - real; positivo = merma', max_digits=12, verbose_name='Diferencia (g)')),
                ('porcentaje_merma', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Merma %')),
                ('ajuste_aplicado', models.BooleanField(default=True, help_text='Si se actualizó el stock de la caramelera al peso real', verbose_name='Ajuste Aplicado')),
                ('motivo', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('auditado_en', models.DateTimeField(auto_now_add=True)),
                ('auditado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias_caramelera', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por')),
                ('caramelera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='granel.caramelera', verbose_name='Caramelera')),
            ],
            options={
                'verbose_name': 'Auditoría de Caramelera',
                'verbose_name_plural': 'Auditorías de Caramelera',
                'ordering': ['-auditado_en'],
            },
        ),
        migrations.CreateModel(
            name='AperturaBulto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_agregados', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gramos Agregados')),
                ('costo_por_gramo_al_abrir', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Costo/g al Abrir')),
                ('costo_ponderado_antes', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Costo Ponderado Antes ($/g)')),
                ('costo_ponderado_despues', models.DecimalField(decimal_places=6, max_digits=12, verbose_name='Costo Ponderado Después ($/g)')),
                ('stock_gramos_antes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Gramos Antes')),
                ('stock_gramos_despues', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock Gramos Después')),
                ('unidades_restantes_deposito', models.IntegerField(help_text='Snapshot del stock del depósito después de abrir', verbose_name='Unidades Restantes en Depósito')),
                ('abierto_en', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('abierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_bulto', to=settings.AUTH_USER_MODEL, verbose_name='Abierto por')),
                ('caramelera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aperturas', to='granel.caramelera', verbose_name='Caramelera')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas', to='granel.productodeposito', verbose_name='Producto Depósito')),
            ],
            options={
                'verbose_name': 'Apertura de Bulto',
                'verbose_name_plural': 'Aperturas de Bulto',
                'ordering': ['-abierto_en'],
            },
        ),
    ]
