# Generated by Django 4.2.27 on 2026-04-03 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_add_caramelera_fields'),
        ('granel', '0006_new_caramelera_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturabulto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aperturas_caramelera', to='stocks.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='caramelera',
            name='productos_autorizados',
            field=models.ManyToManyField(blank=True, help_text='Productos del inventario marcados como "para caramelera" que pueden entrar en este mix', limit_choices_to={'es_deposito_caramelera': True}, to='stocks.product', verbose_name='Productos Autorizados'),
        ),
    ]
