# Generated by Django 4.2.27 on 2026-04-03 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_fix_granel_price_weight_grams'),
        ('granel', '0011_direct_cursor_fix_m2m'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulktograneltransfer',
            name='bulk_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granel_transfers_out', to='stocks.product', verbose_name='Producto Bulto (origen)'),
        ),
        migrations.AlterField(
            model_name='bulktograneltransfer',
            name='granel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granel_transfers_in', to='stocks.product', verbose_name='Producto Granel (destino)'),
        ),
    ]
