# Generated by Django 4.2.27 on 2026-04-03 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_fix_granel_price_weight_grams'),
        ('granel', '0012_fix_bulktogranel_protect_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aperturabulto',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aperturas_caramelera', to='stocks.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='shrinkageaudit',
            name='granel_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shrinkage_audits', to='stocks.product', verbose_name='Producto Granel'),
        ),
    ]
