# Generated by Django 4.2.27 on 2026-04-13 06:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('granel', '0015_fix_aperturabulto_fk_to_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caramelera',
            name='precio_cuarto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio por kilo. Se aplica desde 250g en adelante por regla de tres.', max_digits=10, verbose_name='Precio por Kilo Oferta ($)'),
        ),
        migrations.AlterField(
            model_name='ventagranel',
            name='tipo_venta',
            field=models.CharField(choices=[('kilo', 'Precio por kilo'), ('cuarto', '1/4 kg (250g)'), ('libre', 'Gramos libres')], default='libre', max_length=10, verbose_name='Tipo de Venta'),
        ),
    ]
