# Generated by Django 4.2.27 on 2026-04-13 06:55
"""
Data migration: convert precio_cuarto from price-per-250g to price-per-kg (×4).
Also converts the synced sale_price_250g on Product.
"""
from decimal import Decimal
from django.db import migrations


def convert_to_kilo(apps, schema_editor):
    Caramelera = apps.get_model('granel', 'Caramelera')
    Product = apps.get_model('stocks', 'Product')

    for c in Caramelera.objects.filter(precio_cuarto__gt=0):
        c.precio_cuarto = c.precio_cuarto * Decimal('4')
        c.save(update_fields=['precio_cuarto'])

    # Sync Product.sale_price_250g (stores the same value)
    for p in Product.objects.filter(is_granel=True, sale_price_250g__gt=0):
        p.sale_price_250g = p.sale_price_250g * Decimal('4')
        p.save(update_fields=['sale_price_250g'])


def revert_to_cuarto(apps, schema_editor):
    Caramelera = apps.get_model('granel', 'Caramelera')
    Product = apps.get_model('stocks', 'Product')

    for c in Caramelera.objects.filter(precio_cuarto__gt=0):
        c.precio_cuarto = c.precio_cuarto / Decimal('4')
        c.save(update_fields=['precio_cuarto'])

    for p in Product.objects.filter(is_granel=True, sale_price_250g__gt=0):
        p.sale_price_250g = p.sale_price_250g / Decimal('4')
        p.save(update_fields=['sale_price_250g'])


class Migration(migrations.Migration):

    dependencies = [
        ('granel', '0016_precio_cuarto_to_kilo_oferta'),
        ('stocks', '0018_fix_empty_barcodes_to_null'),
    ]

    operations = [
        migrations.RunPython(convert_to_kilo, revert_to_cuarto),
    ]
