# Generated by Django 3.0.5 on 2026-02-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='color',
            field=models.CharField(default='#6c757d', help_text='Código hexadecimal del color', max_length=7, verbose_name='Color'),
        ),
    ]
