# Generated by Django 4.2.29 on 2026-04-20 06:02

from django.db import migrations, models


def marcar_compras_como_inversion(apps, schema_editor):
    """Marca cualquier categoria llamada 'Compras' (o similar) como inversion.

    El cliente pidio explicitamente que las compras de mercaderia no resten
    del balance porque son inversion, no gasto puro. Este data migration lo
    hace automatico para los datos existentes — si despues crean nuevas
    categorias similares, se marca a mano desde el form.
    """
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseCategory.objects.filter(name__iexact='Compras').update(is_investment=True)
    ExpenseCategory.objects.filter(name__icontains='mercaderia').update(is_investment=True)
    ExpenseCategory.objects.filter(name__icontains='mercadería').update(is_investment=True)


def revertir(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseCategory.objects.all().update(is_investment=False)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expense_id_alter_expensecategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='is_investment',
            field=models.BooleanField(default=False, help_text='Marcá esta opción si los gastos de esta categoría representan inversión y no deben restarse de las ganancias en el balance. Caso típico: Compras de mercadería — ese dinero se convierte en productos para revender, no es un gasto puro del negocio.', verbose_name='Inversión (no resta del balance)'),
        ),
        migrations.RunPython(marcar_compras_como_inversion, revertir),
    ]
