# Generated by Django 3.0.5 on 2026-02-05 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida'),
        ),
    ]
