# Generated by Django 4.2.27 on 2026-03-31 20:01

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_id_alter_purchaseitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('21.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='IVA (%)'),
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se completa, actualiza el precio de venta del producto al recibir', max_digits=10, null=True, verbose_name='Precio de Venta'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='IVA ($)'),
        ),
    ]
