# Generated by Django 4.2.27 on 2026-04-17 07:46

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_fix_empty_barcodes_to_null'),
        ('purchase', '0004_add_tax_percent_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Si se indica, quantity es cantidad de este empaque (bulto/display/unidad). Si es null, quantity es en unidades base.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='stocks.productpackaging', verbose_name='Empaque'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Cantidad expresada en la unidad del empaque seleccionado (o unidades base si no hay empaque).', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, help_text='Costo por unidad del empaque seleccionado (ej: costo del bulto si packaging es bulto).', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Costo Unitario'),
        ),
    ]
