# Generated by Django 3.0.5 on 2026-02-03 08:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: CAJA-01', max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Ubicación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Caja Registradora',
                'verbose_name_plural': 'Cajas Registradoras',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('is_cash', models.BooleanField(default=False, help_text='Si es efectivo, se incluye en arqueo de caja', verbose_name='Es Efectivo')),
                ('icon', models.CharField(default='fa-money-bill', help_text='Clase Font Awesome', max_length=50, verbose_name='Icono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('status', models.CharField(choices=[('open', 'Abierto'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado')),
                ('initial_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Efectivo inicial en caja', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Monto Inicial')),
                ('expected_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Calculado automáticamente', max_digits=10, verbose_name='Monto Esperado')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Conteo real al cierre', max_digits=10, null=True, verbose_name='Monto Real')),
                ('difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sobrante (+) o Faltante (-)', max_digits=10, verbose_name='Diferencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='cashregister.CashRegister', verbose_name='Caja')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Turno de Caja',
                'verbose_name_plural': 'Turnos de Caja',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('income', 'Ingreso'), ('expense', 'Egreso')], max_length=20, verbose_name='Tipo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('description', models.CharField(max_length=200, verbose_name='Descripción')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='cashregister.CashShift', verbose_name='Turno')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='cashregister.PaymentMethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-created_at'],
            },
        ),
    ]
