# Generated by Django 3.0.5 on 2026-02-03 10:02

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='color',
            field=models.CharField(default='#198754', help_text='Color para gráficos', max_length=7, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='requires_counting',
            field=models.BooleanField(default=False, help_text='Si requiere conteo de billetes/monedas al cierre', verbose_name='Requiere Conteo'),
        ),
        migrations.CreateModel(
            name='ShiftPaymentSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Total')),
                ('transaction_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Transacciones')),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_summaries', to='cashregister.CashShift', verbose_name='Turno')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_summaries', to='cashregister.PaymentMethod', verbose_name='Método de Pago')),
            ],
            options={
                'verbose_name': 'Resumen por Método de Pago',
                'verbose_name_plural': 'Resúmenes por Método de Pago',
                'unique_together': {('cash_shift', 'payment_method')},
            },
        ),
        migrations.CreateModel(
            name='BillCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.IntegerField(choices=[(1000, '$1.000'), (2000, '$2.000'), (5000, '$5.000'), (10000, '$10.000'), (20000, '$20.000'), (1, '$1'), (2, '$2'), (5, '$5'), (10, '$10'), (20, '$20'), (50, '$50'), (100, '$100'), (200, '$200'), (500, '$500')], verbose_name='Denominación')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Cantidad')),
                ('count_type', models.CharField(choices=[('opening', 'Apertura'), ('closing', 'Cierre')], default='closing', max_length=20, verbose_name='Tipo de Conteo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_counts', to='cashregister.CashShift', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Conteo de Billetes',
                'verbose_name_plural': 'Conteos de Billetes',
                'ordering': ['-denomination'],
                'unique_together': {('cash_shift', 'denomination', 'count_type')},
            },
        ),
    ]
