# Generated by Django 3.0.5 on 2026-02-03 08:45

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promotions', '0001_initial'),
        ('stocks', '0001_initial'),
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Apertura')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Cierre')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('closed', 'Cerrado')], default='active', max_length=20, verbose_name='Estado')),
                ('cash_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='cashregister.CashShift', verbose_name='Turno de Caja')),
            ],
            options={
                'verbose_name': 'Sesión POS',
                'verbose_name_plural': 'Sesiones POS',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='POSTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='Formato: CAJA-XX-YYYYMMDD-NNNN', max_length=50, unique=True, verbose_name='Número de Ticket')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada'), ('cancelled', 'Cancelada'), ('suspended', 'Suspendida')], default='pending', max_length=20, verbose_name='Estado')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Descuentos')),
                ('tax_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total Impuestos')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Total')),
                ('items_count', models.PositiveIntegerField(default=0, verbose_name='Cantidad de Ítems')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Monto Pagado')),
                ('change_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Vuelto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completada')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Cancelada')),
                ('suspended_at', models.DateTimeField(blank=True, null=True, verbose_name='Suspendida')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.POSSession', verbose_name='Sesión')),
            ],
            options={
                'verbose_name': 'Transacción POS',
                'verbose_name_plural': 'Transacciones POS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuickAccessButton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Nombre corto para el botón. Si vacío, usa el nombre del producto.', max_length=50, verbose_name='Nombre en Botón')),
                ('color', models.CharField(default='#3498db', help_text='Código hexadecimal', max_length=7, verbose_name='Color')),
                ('icon', models.CharField(default='fa-box', help_text='Clase Font Awesome', max_length=50, verbose_name='Icono')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Posición')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_button', to='stocks.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Botón de Acceso Rápido',
                'verbose_name_plural': 'Botones de Acceso Rápido',
                'ordering': ['position', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='POSTransactionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Precio al momento de la venta', max_digits=10, verbose_name='Precio Unitario')),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Descuento')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Subtotal')),
                ('promotion_name', models.CharField(blank=True, help_text='Guardado para histórico', max_length=200, verbose_name='Nombre Promoción')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_items', to='stocks.Product', verbose_name='Producto')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_items', to='promotions.Promotion', verbose_name='Promoción')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.POSTransaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Ítem de Transacción',
                'verbose_name_plural': 'Ítems de Transacción',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='POSPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('reference', models.CharField(blank=True, help_text='Últimos 4 dígitos de tarjeta, etc.', max_length=100, verbose_name='Referencia')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payments', to='cashregister.PaymentMethod', verbose_name='Método de Pago')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.POSTransaction', verbose_name='Transacción')),
            ],
            options={
                'verbose_name': 'Pago POS',
                'verbose_name_plural': 'Pagos POS',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['ticket_number'], name='pos_postran_ticket__059206_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['status'], name='pos_postran_status_2f0710_idx'),
        ),
        migrations.AddIndex(
            model_name='postransaction',
            index=models.Index(fields=['completed_at'], name='pos_postran_complet_6aee00_idx'),
        ),
    ]
