# Generated by Django 3.0.5 on 2026-02-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Venta'), ('cost_sale', 'Venta al Costo'), ('internal_consumption', 'Consumo Interno')], default='sale', max_length=30, verbose_name='Tipo de Transacción'),
        ),
    ]
