# Generated by Django 3.0.5 on 2026-02-05 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_add_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postransactionitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad'),
        ),
    ]
