# Generated by Django 4.2.28 on 2026-03-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20260205_0040'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSKeyboardShortcut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search_focus', 'Enfocar Búsqueda'), ('help', 'Mostrar Ayuda'), ('dashboard', 'Ir al Dashboard'), ('clear_cart', 'Vaciar Carrito'), ('discount', 'Aplicar Descuento'), ('hold', 'Apartar Venta'), ('suspended', 'Ver Apartados'), ('cancel', 'Cancelar Venta'), ('checkout', 'Cobrar (abrir modal)'), ('pay_cash', 'Cobrar Directo — Efectivo'), ('pay_mercadopago', 'Cobrar Directo — Mercado Pago'), ('pay_debit', 'Cobrar Directo — Débito'), ('pay_credit', 'Cobrar Directo — Crédito'), ('pay_transfer', 'Cobrar Directo — Transferencia'), ('cost_sale', 'Venta al Costo'), ('internal_consumption', 'Consumo Interno'), ('reprint', 'Reimprimir Último Ticket'), ('sales_history', 'Historial de Ventas del Turno')], max_length=60, unique=True, verbose_name='Acción')),
                ('key', models.CharField(choices=[('F1', 'F1'), ('F2', 'F2'), ('F3', 'F3'), ('F4', 'F4'), ('F5', 'F5'), ('F6', 'F6'), ('F7', 'F7'), ('F8', 'F8'), ('F9', 'F9'), ('F10', 'F10'), ('F11', 'F11'), ('F12', 'F12'), ('Escape', 'Escape'), ('Alt+1', 'Alt+1'), ('Alt+2', 'Alt+2'), ('Alt+3', 'Alt+3'), ('Alt+4', 'Alt+4'), ('Alt+5', 'Alt+5'), ('Alt+6', 'Alt+6'), ('Alt+7', 'Alt+7'), ('Alt+8', 'Alt+8'), ('Alt+9', 'Alt+9'), ('none', '(Sin atajo)')], default='none', help_text='Tecla asignada a esta acción. Evite duplicados.', max_length=10, verbose_name='Tecla')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden de visualización')),
            ],
            options={
                'verbose_name': 'Atajo de Teclado POS',
                'verbose_name_plural': 'Atajos de Teclado POS',
                'ordering': ['order', 'action'],
            },
        ),
        migrations.AlterField(
            model_name='pospayment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='possession',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='postransactionitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quickaccessbutton',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
