# Generated by Django 4.2.29 on 2026-03-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_add_poskeyboardshortcut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poskeyboardshortcut',
            name='action',
            field=models.CharField(choices=[('search_focus', 'Enfocar Búsqueda'), ('help', 'Mostrar Ayuda'), ('dashboard', 'Ir al Dashboard'), ('clear_cart', 'Vaciar Carrito'), ('discount', 'Aplicar Descuento'), ('hold', 'Apartar Venta'), ('suspended', 'Ver Apartados'), ('cancel', 'Cancelar Venta'), ('checkout', 'Cobrar (abrir modal)'), ('pay_cash', 'Cobrar Directo — Efectivo'), ('pay_mercadopago', 'Cobrar Directo — Mercado Pago'), ('pay_debit', 'Cobrar Directo — Débito'), ('pay_credit', 'Cobrar Directo — Crédito'), ('pay_transfer', 'Cobrar Directo — Transferencia'), ('pay_mixed', 'Cobrar Directo — Mixto (MP + Efectivo)'), ('cost_sale', 'Venta al Costo'), ('internal_consumption', 'Consumo Interno'), ('reprint', 'Reimprimir Último Ticket'), ('sales_history', 'Historial de Ventas del Turno')], max_length=60, unique=True, verbose_name='Acción'),
        ),
    ]
