# Generated by Django 4.2.27 on 2026-03-22 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_alter_stockmovement_quantity'),
        ('pos', '0005_alter_poskeyboardshortcut_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='packaging',
            field=models.ForeignKey(blank=True, help_text='Empaque vendido (unidad/display/bulto). Si es null, se vende 1 unidad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_items', to='stocks.productpackaging', verbose_name='Empaque'),
        ),
        migrations.AddField(
            model_name='postransactionitem',
            name='packaging_units',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas unidades base se descuentan por cada unidad vendida de este empaque', verbose_name='Unidades por Empaque'),
        ),
    ]
