# Generated by Django 4.2.27 on 2026-03-28 22:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_packaging_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='postransactionitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo del producto al momento de la venta (para cálculo de ganancia)', max_digits=10, verbose_name='Costo Unitario'),
        ),
    ]
