# Generated by Django 4.2.27 on 2026-03-30 04:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_add_unit_cost_to_transaction_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postransactionitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad'),
        ),
    ]
