# Generated by Django 3.0.5 on 2026-02-04 04:39

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
        ('cashregister', '0002_add_bill_count_and_payment_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Producción', max_length=100, verbose_name='Nombre')),
                ('access_token', models.CharField(help_text='Token de acceso de Mercado Pago', max_length=500, verbose_name='Access Token')),
                ('public_key', models.CharField(blank=True, help_text='Clave pública (opcional)', max_length=500, verbose_name='Public Key')),
                ('user_id', models.CharField(blank=True, help_text='ID de usuario de MP', max_length=50, verbose_name='User ID')),
                ('is_sandbox', models.BooleanField(default=False, help_text='Usar ambiente de pruebas', verbose_name='Modo Sandbox')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('webhook_secret', models.CharField(blank=True, help_text='Clave secreta para validar webhooks', max_length=200, verbose_name='Webhook Secret')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credencial MP',
                'verbose_name_plural': 'Credenciales MP',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=100, verbose_name='Tipo de Evento')),
                ('event_id', models.CharField(blank=True, max_length=100, verbose_name='ID Evento')),
                ('resource_id', models.CharField(blank=True, max_length=100, verbose_name='ID Recurso')),
                ('payload', models.TextField(blank=True, help_text='JSON payload', verbose_name='Payload')),
                ('headers', models.TextField(blank=True, help_text='JSON headers', verbose_name='Headers')),
                ('processed', models.BooleanField(default=False, verbose_name='Procesado')),
                ('processing_result', models.TextField(blank=True, verbose_name='Resultado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
            ],
            options={
                'verbose_name': 'Log Webhook',
                'verbose_name_plural': 'Logs Webhook',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PointDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='ID del dispositivo en Mercado Pago', max_length=100, unique=True, verbose_name='Device ID')),
                ('device_name', models.CharField(blank=True, max_length=100, verbose_name='Nombre del Dispositivo')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Número de Serie')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('disconnected', 'Desconectado')], default='active', max_length=20, verbose_name='Estado')),
                ('operating_mode', models.CharField(default='PDV', help_text='PDV = Integrado con sistema', max_length=50, verbose_name='Modo de Operación')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Última Sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cash_register', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='point_device', to='cashregister.CashRegister', verbose_name='Caja Asociada')),
            ],
            options={
                'verbose_name': 'Dispositivo Point',
                'verbose_name_plural': 'Dispositivos Point',
                'ordering': ['device_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_reference', models.CharField(help_text='ID único para rastrear el pago', max_length=100, unique=True, verbose_name='Referencia Externa')),
                ('mp_payment_intent_id', models.CharField(blank=True, help_text='ID del payment intent en MP', max_length=100, verbose_name='ID Intent MP')),
                ('mp_payment_id', models.CharField(blank=True, help_text='ID del pago aprobado en MP', max_length=100, verbose_name='ID Pago MP')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1.00'))], verbose_name='Monto')),
                ('description', models.CharField(default='Venta CHE GOLOSO', max_length=200, verbose_name='Descripción')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processing', 'Procesando'), ('approved', 'Aprobada'), ('rejected', 'Rechazada'), ('cancelled', 'Cancelada'), ('error', 'Error'), ('expired', 'Expirada')], default='pending', max_length=20, verbose_name='Estado')),
                ('payment_method', models.CharField(blank=True, help_text='debit_card, credit_card, etc.', max_length=50, verbose_name='Método de Pago')),
                ('card_brand', models.CharField(blank=True, max_length=50, verbose_name='Marca de Tarjeta')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos')),
                ('installments', models.PositiveIntegerField(default=1, verbose_name='Cuotas')),
                ('authorization_code', models.CharField(blank=True, max_length=50, verbose_name='Código de Autorización')),
                ('status_detail', models.CharField(blank=True, max_length=200, verbose_name='Detalle de Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de Error')),
                ('webhook_data', models.TextField(blank=True, help_text='Datos raw recibidos del webhook (JSON)', verbose_name='Datos Webhook')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviado al Point')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completado')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_payment_intents', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='mercadopago.PointDevice', verbose_name='Dispositivo')),
                ('pos_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mp_payment_intents', to='pos.POSTransaction', verbose_name='Transacción POS')),
            ],
            options={
                'verbose_name': 'Intención de Pago',
                'verbose_name_plural': 'Intenciones de Pago',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['external_reference'], name='mercadopago_externa_597dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['mp_payment_intent_id'], name='mercadopago_mp_paym_97f12b_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['mp_payment_id'], name='mercadopago_mp_paym_4224d2_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status'], name='mercadopago_status_055b8a_idx'),
        ),
    ]
