# Generated by Django 4.2.27 on 2026-04-05 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mercadopago', '0003_remove_external_pos_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpcredentials',
            name='external_pos_id',
            field=models.CharField(blank=True, help_text='ID del punto de venta para QR estático. Ej: CHEPOS-001. Debe coincidir con el configurado en MP.', max_length=100, verbose_name='External POS ID (QR)'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment_flow',
            field=models.CharField(choices=[('qr', 'QR Estático'), ('point', 'Point Smart (Tarjeta)')], default='qr', max_length=10, verbose_name='Flujo de Pago'),
        ),
        migrations.AlterField(
            model_name='paymentintent',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='mercadopago.pointdevice', verbose_name='Dispositivo'),
        ),
    ]
