# Generated by Django 3.0.5 on 2026-02-03 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la Empresa')),
                ('legal_name', models.CharField(blank=True, max_length=200, verbose_name='Razón Social')),
                ('cuit', models.CharField(blank=True, max_length=20, verbose_name='CUIT')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Sitio Web')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Logo')),
                ('tax_condition', models.CharField(blank=True, help_text='Ej: Responsable Inscripto, Monotributista', max_length=100, verbose_name='Condición Fiscal')),
                ('gross_income', models.CharField(blank=True, max_length=50, verbose_name='Ingresos Brutos')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Inicio de Actividades')),
                ('receipt_header', models.TextField(blank=True, help_text='Texto que aparece al inicio del ticket', verbose_name='Encabezado de Ticket')),
                ('receipt_footer', models.TextField(blank=True, help_text='Texto que aparece al final del ticket', verbose_name='Pie de Ticket')),
                ('currency_symbol', models.CharField(default='$', max_length=10, verbose_name='Símbolo de Moneda')),
                ('decimal_separator', models.CharField(default=',', max_length=1, verbose_name='Separador Decimal')),
                ('thousands_separator', models.CharField(default='.', max_length=1, verbose_name='Separador de Miles')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresa',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('address', models.TextField(blank=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Teléfono')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('is_main', models.BooleanField(default=False, verbose_name='Sucursal Principal')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.Company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ['-is_main', 'name'],
            },
        ),
    ]
