# Generated by Django 4.2.27 on 2026-03-20 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signage', '0001_reset_legacy'),
        ('stocks', '0007_alter_stockmovement_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SignBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Nombre')),
                ('paper_size', models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('A3', 'A3 (297 × 420 mm)'), ('letter', 'Carta (216 × 279 mm)')], default='A4', max_length=10, verbose_name='Tamaño de Papel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Lote de Carteles',
                'verbose_name_plural': 'Lotes de Carteles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SignTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('sign_type', models.CharField(choices=[('simple', 'Cartel Simple (Precio Unitario)'), ('promo', 'Cartel Promocional (Llevá X por Y)'), ('bulk', 'Cartel de Bulto Cerrado (Caja/Bolsa)'), ('weight', 'Cartel de Venta al Peso')], max_length=20, verbose_name='Tipo de Cartel')),
                ('width_mm', models.PositiveIntegerField(verbose_name='Ancho (mm)')),
                ('height_mm', models.PositiveIntegerField(verbose_name='Alto (mm)')),
                ('layout_json', models.TextField(blank=True, default='{}', verbose_name='Diseño (JSON)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_default', models.BooleanField(default=False, verbose_name='Predeterminado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Plantilla de Cartel',
                'verbose_name_plural': 'Plantillas de Carteles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SignItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.TextField(blank=True, default='{}', verbose_name='Datos (JSON)')),
                ('copies', models.PositiveIntegerField(default=1, verbose_name='Copias')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='signage.signbatch', verbose_name='Lote')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stocks.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Cartel',
                'verbose_name_plural': 'Items de Carteles',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='signbatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='signage.signtemplate', verbose_name='Plantilla'),
        ),
    ]
