# Generated by Django 4.2.27 on 2026-02-05 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, help_text='Clave API de OpenAI (sk-...)', max_length=200, verbose_name='OpenAI API Key')),
                ('model', models.CharField(default='gpt-4o-mini', help_text='Modelo de OpenAI a usar', max_length=50, verbose_name='Modelo')),
                ('max_tokens', models.IntegerField(default=2000, help_text='Máximo de tokens por respuesta', verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.7, help_text='Creatividad (0.0 - 1.0)', verbose_name='Temperatura')),
                ('system_prompt', models.TextField(blank=True, help_text='Instrucciones base para el asistente', verbose_name='Prompt del Sistema')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Asistente',
                'verbose_name_plural': 'Configuración del Asistente',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistant_conversations', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Conversación',
                'verbose_name_plural': 'Conversaciones',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(verbose_name='Consulta')),
                ('query_type', models.CharField(blank=True, max_length=50, verbose_name='Tipo de consulta')),
                ('response_time_ms', models.IntegerField(default=0, verbose_name='Tiempo de respuesta (ms)')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('was_successful', models.BooleanField(default=True, verbose_name='Exitosa')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Consulta',
                'verbose_name_plural': 'Logs de Consultas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], max_length=20, verbose_name='Rol')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('tokens_used', models.IntegerField(default=0, verbose_name='Tokens usados')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='assistant.conversation', verbose_name='Conversación')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['created_at'],
            },
        ),
    ]
