# Generated by Django 4.2.28 on 2026-03-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_auto_20260205_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='model',
            field=models.CharField(default='gemini-2.0-flash', help_text='Modelo de Gemini a usar', max_length=50, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='assistantsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, help_text='Clave API de Google Gemini (AIza...)', max_length=200, verbose_name='API Key de Gemini'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
