# Generated by Django 4.2.27 on 2026-03-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_alter_assistantsettings_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistantsettings',
            name='model',
            field=models.CharField(default='gemini-2.5-flash', help_text='Modelo de Gemini a usar', max_length=50, verbose_name='Modelo'),
        ),
    ]
