# Generated by Django 3.0.5 on 2026-02-03 08:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta')),
                ('cost_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo Promedio')),
                ('current_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock Actual')),
                ('min_stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Alerta cuando el stock llegue a este nivel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock Mínimo')),
                ('max_stock', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Stock Máximo')),
                ('location', models.CharField(blank=True, help_text='Ubicación física en el almacén', max_length=50, verbose_name='Ubicación')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_quick_access', models.BooleanField(default=False, help_text='Mostrar como botón de acceso rápido en el POS', verbose_name='Acceso Rápido POS')),
                ('quick_access_color', models.CharField(default='#3498db', help_text='Código hexadecimal del color para botón POS', max_length=7, verbose_name='Color Acceso Rápido')),
                ('quick_access_icon', models.CharField(default='fa-box', help_text='Clase de icono Font Awesome', max_length=50, verbose_name='Icono Acceso Rápido')),
                ('quick_access_position', models.PositiveIntegerField(default=0, verbose_name='Posición Acceso Rápido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('abbreviation', models.CharField(max_length=10, verbose_name='Abreviatura')),
                ('symbol', models.CharField(blank=True, max_length=5, verbose_name='Símbolo')),
                ('unit_type', models.CharField(choices=[('unit', 'Unidad'), ('weight', 'Peso'), ('volume', 'Volumen'), ('length', 'Longitud')], default='unit', max_length=20, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase', 'Compra'), ('sale', 'Venta'), ('adjustment_in', 'Ajuste Entrada'), ('adjustment_out', 'Ajuste Salida'), ('transfer_in', 'Transferencia Entrada'), ('transfer_out', 'Transferencia Salida'), ('return_in', 'Devolución Entrada'), ('return_out', 'Devolución Salida')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Costo Unitario')),
                ('stock_before', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Stock Antes')),
                ('stock_after', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=10, verbose_name='Stock Después')),
                ('reference', models.CharField(blank=True, help_text='Ej: Compra #123, Venta #456', max_length=100, verbose_name='Referencia')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Referencia')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='stocks.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Pack x 6, Caja x 12', max_length=100, verbose_name='Nombre')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad de Unidades')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio de Venta')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='stocks.Product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
                'ordering': ['product', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('default_margin_percent', models.DecimalField(decimal_places=2, default=30.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Margen por defecto (%)')),
                ('color', models.CharField(default='#3498db', help_text='Código hexadecimal del color', max_length=7, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='stocks.ProductCategory', verbose_name='Categoría Padre')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stocks.ProductCategory', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_of_measure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='stocks.UnitOfMeasure', verbose_name='Unidad de Medida'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='stocks_prod_sku_a1f22a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['barcode'], name='stocks_prod_barcode_d19822_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='stocks_prod_name_662e7e_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active'], name='stocks_prod_is_acti_adf660_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['current_stock'], name='stocks_prod_current_7c1ee1_idx'),
        ),
    ]
