# Generated by Django 3.0.5 on 2026-02-03 10:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_sell_by_amount',
            field=models.BooleanField(default=False, help_text='Permite ingresar "$500 de gomitas" y calcular la cantidad', verbose_name='Permite Venta por Monto'),
        ),
        migrations.AddField(
            model_name='product',
            name='bulk_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogramo'), ('g', 'Gramo'), ('lt', 'Litro'), ('ml', 'Mililitro')], default='kg', max_length=10, verbose_name='Unidad de Granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='Productos que se venden por peso (gomitas, fiambres, etc)', verbose_name='Producto a Granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_product',
            field=models.ForeignKey(blank=True, help_text='Para cajas/bultos, indica el producto individual que contiene', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_products', to='stocks.Product', verbose_name='Producto Padre'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_package',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Cuántas unidades del producto hijo contiene (ej: 24 para caja de 24)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Unidades por Paquete'),
        ),
    ]
