# Generated by Django 3.0.5 on 2026-02-05 03:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_add_bulk_and_parent_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_stock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Stock Máximo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_stock',
            field=models.PositiveIntegerField(default=0, help_text='Alerta cuando el stock llegue a este nivel', verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='units_per_package',
            field=models.PositiveIntegerField(default=1, help_text='Cuántas unidades del producto hijo contiene (ej: 24 para caja de 24)', verbose_name='Unidades por Paquete'),
        ),
        migrations.AlterField(
            model_name='productpresentation',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad de Unidades'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_after',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Después'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_before',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Antes'),
        ),
    ]
