# Generated by Django 4.2.28 on 2026-02-07 22:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20260205_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productpresentation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ProductPackaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packaging_type', models.CharField(choices=[('unit', 'Unidad'), ('display', 'Display/Paquete'), ('bulk', 'Bulto/Caja')], max_length=20, verbose_name='Tipo de Empaque')),
                ('barcode', models.CharField(help_text='Código de barras para este empaque', max_length=50, unique=True, verbose_name='Código de Barras')),
                ('name', models.CharField(help_text='Ej: Unidad, Display x 12, Bulto x 144', max_length=100, verbose_name='Nombre')),
                ('units_quantity', models.PositiveIntegerField(default=1, help_text='Cuántas unidades base contiene este empaque', verbose_name='Cantidad de Unidades')),
                ('units_per_display', models.PositiveIntegerField(default=1, help_text='Cuántas unidades contiene cada display', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Unidades por Display')),
                ('displays_per_bulk', models.PositiveIntegerField(default=1, help_text='Cuántos displays contiene cada bulto', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Displays por Bulto')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de Compra')),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Precio de Venta')),
                ('calculate_margin_on', models.CharField(choices=[('unit', 'Unidad'), ('display', 'Display/Paquete'), ('bulk', 'Bulto/Caja')], default='bulk', help_text='Sobre qué empaque se calcula el porcentaje de ganancia', max_length=20, verbose_name='Calcular Ganancia Sobre')),
                ('margin_percent', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Margen de Ganancia (%)')),
                ('is_default', models.BooleanField(default=False, help_text='Usar por defecto en POS', verbose_name='Empaque por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packagings', to='stocks.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Empaque de Producto',
                'verbose_name_plural': 'Empaques de Productos',
                'ordering': ['product', 'packaging_type'],
            },
        ),
    ]
