# Generated by Django 4.2.28 on 2026-03-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_product_id_alter_productcategory_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='current_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Actual'),
        ),
    ]
