# Generated by Django 4.2.28 on 2026-03-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_change_current_stock_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Después'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='stock_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Stock Antes'),
        ),
    ]
