# Generated by Django 4.2.28 on 2026-03-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_change_stock_movement_fields_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Cantidad'),
        ),
    ]
