# Generated by Django 4.2.27 on 2026-03-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_productpackaging_current_stock_min_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpackaging',
            name='barcode',
            field=models.CharField(blank=True, help_text='Código de barras para este empaque', max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
