# Generated by Django 4.2.27 on 2026-03-30 04:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_productpackaging_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granel_price_weight_grams',
            field=models.PositiveIntegerField(default=100, help_text='El sale_price es "por cada X gramos" (ej: 100 = $2500/100g)', verbose_name='Precio por X gramos'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_granel',
            field=models.BooleanField(default=False, help_text='Producto comodín que recibe stock de bultos abiertos (ej: Gomitas Surtidas)', verbose_name='Producto Comodín Granel'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_per_unit_grams',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Para bultos: gramos que contiene cada unidad (ej: 2000 para bolsa de 2kg)', max_digits=10, verbose_name='Peso por Unidad (gramos)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weighted_avg_cost_per_gram',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Costo promedio ponderado por gramo, calculado automáticamente', max_digits=12, verbose_name='Costo Ponderado por Gramo'),
        ),
    ]
