# Generated by Django 4.2.27 on 2026-03-31 01:35

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchase_id_alter_purchaseitem_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stocks', '0010_product_granel_price_weight_grams_product_is_granel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('quantity_purchased', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad Comprada')),
                ('quantity_remaining', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cantidad Restante')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Costo Unitario')),
                ('purchased_at', models.DateTimeField(verbose_name='Fecha de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stock_batches', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='stocks.product', verbose_name='Producto')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_batches', to='purchase.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Lote de Stock',
                'verbose_name_plural': 'Lotes de Stock',
                'ordering': ['purchased_at', 'created_at'],
            },
        ),
    ]
