# Generated by Django 4.2.27 on 2026-04-02 21:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_add_stockbatch_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sale_price_250g',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Precio de venta por 250g (1/4 kg)', max_digits=10, verbose_name='Precio por 250g'),
        ),
    ]
