# Generated by Django 4.2.27 on 2026-04-03 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('granel', '0006_new_caramelera_system'),
        ('stocks', '0012_product_sale_price_250g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='granel_caramelera',
            field=models.ForeignKey(blank=True, help_text='Caramelera del sistema granel asociada a este producto POS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_pos', to='granel.caramelera', verbose_name='Caramelera vinculada'),
        ),
    ]
