# Generated by Django 4.2.27 on 2026-04-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_new_caramelera_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='es_deposito_caramelera',
            field=models.BooleanField(default=False, help_text='Marca este producto como un bulto que puede abrirse en una caramelera', verbose_name='Es producto para caramelera'),
        ),
        migrations.AddField(
            model_name='product',
            name='marca',
            field=models.CharField(blank=True, help_text='Marca del producto (útil para diferenciar bultos en carameleras)', max_length=200, verbose_name='Marca'),
        ),
    ]
