# Generated by Django 4.2.27 on 2026-04-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_fix_granel_price_weight_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='SKU'),
        ),
    ]
