# Generated by Django 4.2.27 on 2026-04-17 18:47

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_fix_empty_barcodes_to_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Margen por defecto (%)'),
        ),
        migrations.AlterField(
            model_name='productpackaging',
            name='margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Margen de Ganancia (%)'),
        ),
    ]
